### ISSUE TITLE
Install requirements.txt missing 

### ISSUE THREAD

**Issue by Inferencer** [andrerochow/fsrt#4]
until the reqs are uploaded i did this to get it working
as im using cuda 11.8 i did this for the pytorch
`conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia`

then the other reqs are as follows

`pip install tqdm`
`pip install matplotlib`
`pip install einops`
`pip install ffmpeg`
`pip install imageio[ffmpeg]`
`pip install imageio[pyav]`

for the checkpoints i put the kp_detector in a new folder called weights
./weights/kp_detector.pt
and 
./fsrt_checkpoints/vox256.pt

I also create a folder called examples to keep the driving and source in ill provide them here 

https://drive.google.com/drive/folders/1a0lk0NUqwDj8-2OzDgGcGU2cOGRuSGAT?usp=sharing

**Comment by andrerochow** [comment]
Hello and thanks for the hint!

The requirements.txt is now available in the repository.
