### ISSUE TITLE
Does it support only 256 x 256 only?

### ISSUE THREAD

**Issue by nitinmukesh** [andrerochow/fsrt#7]
As the title says

In code
resize(img, (256, 256)

Can't we use high resolution images?

[EDIT]
The models are trained for 256 x 256 
vox256.pt

**Comment by Inferencer** [comment]
> As the title says
> 
> In code resize(img, (256, 256)
> 
> Can't we use high resolution images?
> 
> [EDIT] The models are trained for 256 x 256 vox256.pt

use liveportrait repo its current sota and 512

**Comment by mhwu2017** [comment]
> > As the title says
> > In code resize(img, (256, 256)
> > Can't we use high resolution images?
> > [EDIT] The models are trained for 256 x 256 vox256.pt
> 
> use liveportrait repo its current sota and 512

I tried liveportrait, it works really well in general. But when the first frame is not neutral exp, the result is worse. How can I solve it?
